OPENMETADATA_SUPPORTED_DATATYPES = [
    "NUMBER",
    "TINYINT",
    "SMALLINT",
    "INT",
    "BIGINT",
    "BYTEINT",
    "BYTES",
    "FLOAT",
    "DOUBLE",
    "DECIMAL",
    "NUMERIC",
    "TIMESTAMP",
    "TIMESTAMPZ",
    "TIME",
    "DATE",
    "DATETIME",
    "INTERVAL",
    "STRING",
    "MEDIUMTEXT",
    "TEXT",
    "CHAR",
    "LONG",
    "VARCHAR",
    "BOOLEAN",
    "BINARY",
    "VARBINARY",
    "ARRAY",
    "BLOB",
    "LONGBLOB",
    "MEDIUMBLOB",
    "MAP",
    "STRUCT",
    "UNION",
    "SET",
    "GEOGRAPHY",
    "ENUM",
    "JSON",
    "UUID",
    "VARIANT",
    "GEOMETRY",
    "POINT",
    "POLYGON",
    "BYTEA",
]

# `infrastructureTemplateId` that discriminates the workload component this
# adapter provisions from any other workload (e.g. the nested Databricks Guardian
# workload embedded in the same descriptor, which is owned by a different adapter).
SODA_TECH_ADAPTER_INFRASTRUCTURE_TEMPLATE_ID = "urn:dmb:itm:soda-tech-adapter:0"
