apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: fake-soda
spec:
  provider:
    fake:
      data:
        - key: "soda-tech-adapter-provisioner"
          valueMap:
            SODA_API_KEY_ID: id
            SODA_API_KEY_SECRET: secret
